[package]
name = "TagUtils"
authors = [
	"Olivier Trepanier <otrepanier@roblox.com>"
]
license = "MIT"
content_root = "src"
version = "0.1.0"
files = ["*", "!**/__tests__/**"]

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.2.0"
